import colors from '../../constants/colors';
import dimens from '../../constants/dimens';
import React from 'react';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    paddingTop: 50,
    paddingBottom: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 1000,
    width: '100%',
  },
  txtLogo: {
    position: 'absolute',
    top: 200,
    color: colors.white,
    left: 0,
    zIndex: 1000,
    paddingHorizontal: 30,
    width: '100%',
    textAlign: 'center',
    fontSize: dimens.fontLarge,
    fontWeight: 'bold',
  },
  txtNote: {
    position: 'absolute',
    top: 150,
    color: colors.white,
    zIndex: 1000,
    textAlign: 'center',
    paddingHorizontal: 30,
    fontSize: dimens.fontNormal,
  },
  btnContain: {
    position: 'absolute',
    top: 650,
    zIndex: 1000,
    flex: 1,
    width: '100%',
    paddingHorizontal: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDiscount: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: 20,
    marginRight: 20,
    flex: 1,
  },
  btnQr: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: 20,
    flex: 1,
  },
  btnBottomContain: {
    position: 'absolute',
    top: 720,
    zIndex: 1000,
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnApplePay: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 20,
    flex: 1,
  },
  txtApple: {
    color: colors.white,
    fontSize: dimens.fontXSmall,
    marginTop: 5,
    textAlign: 'center',
    flex: 1,
  },
  imageApplePay: { width: 60, height: 30, marginRight: 5, borderRadius: 10 },
  icon: { marginRight: 5 },
  imageDiscount: { width: 40, height: 20, marginRight: 5 },
  txtQr: { alignSelf: 'center', color: colors.white, fontSize: 15 },
  listImage: {
    flexDirection: 'row',
    position: 'absolute',
    top: 580,
    zIndex: 1000,
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  line: { height: 25, width: 0.5, backgroundColor: colors.white, marginHorizontal: 5 },
  vnPay: { width: 70, height: 40, marginLeft: 5 },
  napas: { width: 80, height: 40 },
  vietQr: { width: 65, height: 30 },
});

export default styles;
