
export const listBank = [
    {
        "bin": "970415",
        "code": "ICB",
        "id": 17,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/ICB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Công thương Việt Nam",
        "shortName": "VietinBank",
        "short_name": "VietinBank",
        "support": 3,
        "swift_code": "ICBVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970436",
        "code": "VCB",
        "id": 43,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Ngoại Thương Việt Nam",
        "shortName": "Vietcombank",
        "short_name": "Vietcombank",
        "support": 3,
        "swift_code": "BFTVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970418",
        "code": "BIDV",
        "id": 4,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/BIDV.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
        "shortName": "BIDV",
        "short_name": "BIDV",
        "support": 3,
        "swift_code": "BIDVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970405",
        "code": "VBA",
        "id": 42,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VBA.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
        "shortName": "Agribank",
        "short_name": "Agribank",
        "support": 3,
        "swift_code": "VBAAVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970448",
        "code": "OCB",
        "id": 26,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/OCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Phương Đông",
        "shortName": "OCB",
        "short_name": "OCB",
        "support": 3,
        "swift_code": "ORCOVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970422",
        "code": "MB",
        "id": 21,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/MB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Quân đội",
        "shortName": "MBBank",
        "short_name": "MBBank",
        "support": 3,
        "swift_code": "MSCBVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970407",
        "code": "TCB",
        "id": 38,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/TCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Kỹ thương Việt Nam",
        "shortName": "Techcombank",
        "short_name": "Techcombank",
        "support": 3,
        "swift_code": "VTCBVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970416",
        "code": "ACB",
        "id": 2,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/ACB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Á Châu",
        "shortName": "ACB",
        "short_name": "ACB",
        "support": 3,
        "swift_code": "ASCBVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970432",
        "code": "VPB",
        "id": 47,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VPB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Việt Nam Thịnh Vượng",
        "shortName": "VPBank",
        "short_name": "VPBank",
        "support": 3,
        "swift_code": "VPBKVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970423",
        "code": "TPB",
        "id": 39,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/TPB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Tiên Phong",
        "shortName": "TPBank",
        "short_name": "TPBank",
        "support": 3,
        "swift_code": "TPBVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970403",
        "code": "STB",
        "id": 36,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/STB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Sài Gòn Thương Tín",
        "shortName": "Sacombank",
        "short_name": "Sacombank",
        "support": 3,
        "swift_code": "SGTTVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970437",
        "code": "HDB",
        "id": 12,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/HDB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
        "shortName": "HDBank",
        "short_name": "HDBank",
        "support": 3,
        "swift_code": "HDBCVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970454",
        "code": "VCCB",
        "id": 44,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VCCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Bản Việt",
        "shortName": "VietCapitalBank",
        "short_name": "VietCapitalBank",
        "support": 3,
        "swift_code": "VCBCVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970429",
        "code": "SCB",
        "id": 31,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/SCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Sài Gòn",
        "shortName": "SCB",
        "short_name": "SCB",
        "support": 3,
        "swift_code": "SACLVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970441",
        "code": "VIB",
        "id": 45,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VIB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Quốc tế Việt Nam",
        "shortName": "VIB",
        "short_name": "VIB",
        "support": 3,
        "swift_code": "VNIBVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970443",
        "code": "SHB",
        "id": 35,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/SHB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Sài Gòn - Hà Nội",
        "shortName": "SHB",
        "short_name": "SHB",
        "support": 3,
        "swift_code": "SHBAVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970431",
        "code": "EIB",
        "id": 10,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/EIB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
        "shortName": "Eximbank",
        "short_name": "Eximbank",
        "support": 3,
        "swift_code": "EBVIVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970426",
        "code": "MSB",
        "id": 22,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/MSB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Hàng Hải",
        "shortName": "MSB",
        "short_name": "MSB",
        "support": 3,
        "swift_code": "MCOBVNVX",
        "transferSupported": 1
    },
    {
        "bin": "546034",
        "code": "CAKE",
        "id": 53,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/CAKE.png",
        "lookupSupported": 1,
        "name": "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
        "shortName": "CAKE",
        "short_name": "CAKE",
        "support": 3,
        "swift_code": null,
        "transferSupported": 1
    },
    {
        "bin": "546035",
        "code": "Ubank",
        "id": 54,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/UBANK.png",
        "lookupSupported": 1,
        "name": "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank",
        "shortName": "Ubank",
        "short_name": "Ubank",
        "support": 3,
        "swift_code": null,
        "transferSupported": 1
    },
    {
        "bin": "963388",
        "code": "TIMO",
        "id": 58,
        "isTransfer": 1,
        "logo_url": "https://vietqr.net/portal-service/resources/icons/TIMO.png",
        "lookupSupported": 0,
        "name": "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)",
        "shortName": "Timo",
        "short_name": "Timo",
        "support": 0,
        "swift_code": null,
        "transferSupported": 1
    },
    {
        "bin": "971005",
        "code": "VTLMONEY",
        "id": 57,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/VIETTELMONEY.png",
        "lookupSupported": 1,
        "name": "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội",
        "shortName": "ViettelMoney",
        "short_name": "ViettelMoney",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "971011",
        "code": "VNPTMONEY",
        "id": 56,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/VNPTMONEY.png",
        "lookupSupported": 1,
        "name": "VNPT Money",
        "shortName": "VNPTMoney",
        "short_name": "VNPTMoney",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970400",
        "code": "SGICB",
        "id": 34,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/SGICB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Sài Gòn Công Thương",
        "shortName": "SaigonBank",
        "short_name": "SaigonBank",
        "support": 3,
        "swift_code": "SBITVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970409",
        "code": "BAB",
        "id": 3,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/BAB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Bắc Á",
        "shortName": "BacABank",
        "short_name": "BacABank",
        "support": 3,
        "swift_code": "NASCVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970412",
        "code": "PVCB",
        "id": 30,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/PVCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Đại Chúng Việt Nam",
        "shortName": "PVcomBank",
        "short_name": "PVcomBank",
        "support": 3,
        "swift_code": "WBVNVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970414",
        "code": "Oceanbank",
        "id": 27,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/OCEANBANK.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Thương mại TNHH MTV Đại Dương",
        "shortName": "Oceanbank",
        "short_name": "Oceanbank",
        "support": 3,
        "swift_code": "OCBKUS3M",
        "transferSupported": 1
    },
    {
        "bin": "970419",
        "code": "NCB",
        "id": 24,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/NCB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Quốc Dân",
        "shortName": "NCB",
        "short_name": "NCB",
        "support": 3,
        "swift_code": "NVBAVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970424",
        "code": "SHBVN",
        "id": 37,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/SHBVN.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV Shinhan Việt Nam",
        "shortName": "ShinhanBank",
        "short_name": "ShinhanBank",
        "support": 3,
        "swift_code": "SHBKVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970425",
        "code": "ABB",
        "id": 1,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/ABB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP An Bình",
        "shortName": "ABBANK",
        "short_name": "ABBANK",
        "support": 3,
        "swift_code": "ABBKVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970427",
        "code": "VAB",
        "id": 41,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VAB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Việt Á",
        "shortName": "VietABank",
        "short_name": "VietABank",
        "support": 3,
        "swift_code": "VNACVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970428",
        "code": "NAB",
        "id": 23,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/NAB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Nam Á",
        "shortName": "NamABank",
        "short_name": "NamABank",
        "support": 3,
        "swift_code": "NAMAVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970430",
        "code": "PGB",
        "id": 29,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/PGB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Xăng dầu Petrolimex",
        "shortName": "PGBank",
        "short_name": "PGBank",
        "support": 3,
        "swift_code": "PGBLVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970433",
        "code": "VIETBANK",
        "id": 46,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/VIETBANK.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Việt Nam Thương Tín",
        "shortName": "VietBank",
        "short_name": "VietBank",
        "support": 3,
        "swift_code": "VNTTVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970438",
        "code": "BVB",
        "id": 5,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/BVB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Bảo Việt",
        "shortName": "BaoVietBank",
        "short_name": "BaoVietBank",
        "support": 3,
        "swift_code": "BVBVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970440",
        "code": "SEAB",
        "id": 33,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/SEAB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Đông Nam Á",
        "shortName": "SeABank",
        "short_name": "SeABank",
        "support": 3,
        "swift_code": "SEAVVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970446",
        "code": "COOPBANK",
        "id": 52,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/COOPBANK.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Hợp tác xã Việt Nam",
        "shortName": "COOPBANK",
        "short_name": "COOPBANK",
        "support": 3,
        "swift_code": null,
        "transferSupported": 1
    },
    {
        "bin": "970449",
        "code": "LPB",
        "id": 20,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/LPB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Bưu Điện Liên Việt",
        "shortName": "LienVietPostBank",
        "short_name": "LienVietPostBank",
        "support": 3,
        "swift_code": "LVBKVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970452",
        "code": "KLB",
        "id": 19,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/KLB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Kiên Long",
        "shortName": "KienLongBank",
        "short_name": "KienLongBank",
        "support": 3,
        "swift_code": "KLBKVNVX",
        "transferSupported": 1
    },
    {
        "bin": "668888",
        "code": "KBank",
        "id": 55,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/KBANK.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Đại chúng TNHH Kasikornbank",
        "shortName": "KBank",
        "short_name": "KBank",
        "support": 3,
        "swift_code": "KASIVNVX",
        "transferSupported": 1
    },
    {
        "bin": "970462",
        "code": "KBHN",
        "id": 50,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/KBHN.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Kookmin - Chi nhánh Hà Nội",
        "shortName": "KookminHN",
        "short_name": "KookminHN",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970466",
        "code": "KEBHANAHCM",
        "id": 60,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/KEBHANAHCM.png",
        "lookupSupported": 0,
        "name": "Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh",
        "shortName": "KEBHanaHCM",
        "short_name": "KEBHanaHCM",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970467",
        "code": "KEBHANAHN",
        "id": 61,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/KEBHANAHN.png",
        "lookupSupported": 0,
        "name": "Ngân hàng KEB Hana – Chi nhánh Hà Nội",
        "shortName": "KEBHANAHN",
        "short_name": "KEBHANAHN",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "977777",
        "code": "MAFC",
        "id": 62,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/MAFC.png",
        "lookupSupported": 0,
        "name": "Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) ",
        "shortName": "MAFC",
        "short_name": "MAFC",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "533948",
        "code": "CITIBANK",
        "id": 59,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/CITIBANK.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội",
        "shortName": "Citibank",
        "short_name": "Citibank",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970463",
        "code": "KBHCM",
        "id": 51,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/KBHCM.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh",
        "shortName": "KookminHCM",
        "short_name": "KookminHCM",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "999888",
        "code": "VBSP",
        "id": 63,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/VBSP.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Chính sách Xã hội",
        "shortName": "VBSP",
        "short_name": "VBSP",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970457",
        "code": "WVN",
        "id": 49,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/WVN.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV Woori Việt Nam",
        "shortName": "Woori",
        "short_name": "Woori",
        "support": 0,
        "swift_code": null,
        "transferSupported": 1
    },
    {
        "bin": "970421",
        "code": "VRB",
        "id": 48,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/VRB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Liên doanh Việt - Nga",
        "shortName": "VRB",
        "short_name": "VRB",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970458",
        "code": "UOB",
        "id": 40,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/UOB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh",
        "shortName": "UnitedOverseas",
        "short_name": "UnitedOverseas",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970410",
        "code": "SCVN",
        "id": 32,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/SCVN.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam",
        "shortName": "StandardChartered",
        "short_name": "StandardChartered",
        "support": 0,
        "swift_code": "SCBLVNVX",
        "transferSupported": 0
    },
    {
        "bin": "970439",
        "code": "PBVN",
        "id": 28,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/PBVN.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV Public Việt Nam",
        "shortName": "PublicBank",
        "short_name": "PublicBank",
        "support": 0,
        "swift_code": "VIDPVNVX",
        "transferSupported": 0
    },
    {
        "bin": "801011",
        "code": "NHB HN",
        "id": 25,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/NHB.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Nonghyup - Chi nhánh Hà Nội",
        "shortName": "Nonghyup",
        "short_name": "Nonghyup",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970434",
        "code": "IVB",
        "id": 18,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/IVB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH Indovina",
        "shortName": "IndovinaBank",
        "short_name": "IndovinaBank",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970456",
        "code": "IBK - HCM",
        "id": 16,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/IBK.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh",
        "shortName": "IBKHCM",
        "short_name": "IBKHCM",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "970455",
        "code": "IBK - HN",
        "id": 15,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/IBK.png",
        "lookupSupported": 0,
        "name": "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội",
        "shortName": "IBKHN",
        "short_name": "IBKHN",
        "support": 0,
        "swift_code": null,
        "transferSupported": 0
    },
    {
        "bin": "458761",
        "code": "HSBC",
        "id": 14,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/HSBC.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV HSBC (Việt Nam)",
        "shortName": "HSBC",
        "short_name": "HSBC",
        "support": 0,
        "swift_code": "HSBCVNVX",
        "transferSupported": 0
    },
    {
        "bin": "970442",
        "code": "HLBVN",
        "id": 13,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/HLBVN.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV Hong Leong Việt Nam",
        "shortName": "HongLeong",
        "short_name": "HongLeong",
        "support": 0,
        "swift_code": "HLBBVNVX",
        "transferSupported": 0
    },
    {
        "bin": "970408",
        "code": "GPB",
        "id": 11,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/GPB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu",
        "shortName": "GPBank",
        "short_name": "GPBank",
        "support": 0,
        "swift_code": "GBNKVNVX",
        "transferSupported": 0
    },
    {
        "bin": "970406",
        "code": "DOB",
        "id": 9,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/DOB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TMCP Đông Á",
        "shortName": "DongABank",
        "short_name": "DongABank",
        "support": 0,
        "swift_code": "EACBVNVX",
        "transferSupported": 0
    },
    {
        "bin": "796500",
        "code": "DBS",
        "id": 8,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/DBS.png",
        "lookupSupported": 0,
        "name": "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh",
        "shortName": "DBSBank",
        "short_name": "DBSBank",
        "support": 0,
        "swift_code": "DBSSVNVX",
        "transferSupported": 0
    },
    {
        "bin": "422589",
        "code": "CIMB",
        "id": 7,
        "isTransfer": 1,
        "logo_url": "https://api.vietqr.io/img/CIMB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng TNHH MTV CIMB Việt Nam",
        "shortName": "CIMB",
        "short_name": "CIMB",
        "support": 0,
        "swift_code": "CIBBVNVN",
        "transferSupported": 1
    },
    {
        "bin": "970444",
        "code": "CBB",
        "id": 6,
        "isTransfer": 0,
        "logo_url": "https://api.vietqr.io/img/CBB.png",
        "lookupSupported": 1,
        "name": "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam",
        "shortName": "CBBank",
        "short_name": "CBBank",
        "support": 0,
        "swift_code": "GTBAVNVX",
        "transferSupported": 0
    }
]